<?php

use Magento\Framework\App\Action\Action;

/**
 * Copyright © 2019 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 * cf_theme extension
 * NOTICE OF LICENSE
 *
 * @category Magenest
 * @package cf_theme
 * @package linhphung
 *//** @var $block Magenest\Widget\Block\Product\Widget\ProductListTabs */;
$tabs = $block->getListProductTabs();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);

$type = 'widget-product-grid';

$mode = 'grid';

$image = 'new_products_content_widget_grid';

$showWishlist = true;
$showCompare = true;
$showCart = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$description = false;
?>

<div id="tabs">
    <ul>
        <?php foreach ($tabs as $key => $value): ?>
            <li><a href="#tabs-<?= $key ?>"><?= $value['title'] ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php foreach ($tabs as $key => $value): ?>
        <div id="tabs-<?= $key ?>">
            <?php $products = $value['products']; ?>
            <?php if ($products): ?>
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($products as $_product): ?>
                    <?php $iterator = 1; ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                    <div class="product-item-info">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>" class="product-item-photo">
                            <?= $block->getImage($_product, $image)->toHtml() ?>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtml($_product->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_product->getName()) ?>
                                </a>
                            </strong>
                            <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                <div class="product-item-inner">
                                    <div class="product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_product->isSaleable()) : ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                    <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                                        <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                        <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                        <?= $block->getBlockHtml('formkey') ?>
                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                                class="action tocart primary">
                                                            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                        </button>
                                                    </form>
                                                <?php else : ?>
                                                    <?php if ($_product->getIsSalable()) : ?>
                                                        <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                    <a href="#"
                                                       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                    <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                    <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                        <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?= ($iterator == count($products) + 1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>

</div>


<script>
    require([
        'jquery',
        'tabs'], function ($) {
        $("#tabs").tabs();
    });
</script>
